name: Trello-Google Calendar Sync

on:
  schedule:
    - cron: '*/10 * * * *' # Runs every 10 minutes
  workflow_dispatch:      # Allows the workflow to be manually triggered

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Restore cached token.pickle
        id: cache-token
        uses: actions/cache@v3
        with:
          path: token.pickle
          key: token-cache
      - name: Set up environment variables
        run: |
          echo "Setting environment variables..."
          echo "TRELLO_API_KEY=${{ secrets.TRELLO_API_KEY }}"
          echo "TRELLO_API_TOKEN=${{ secrets.TRELLO_API_TOKEN }}"
          echo "TRELLO_BOARD_ID=${{ secrets.TRELLO_BOARD_ID }}"
          echo "TRELLO_WORKING_LIST_ID=${{ secrets.TRELLO_WORKING_LIST_ID }}"
          echo "TRELLO_DONE_LIST_ID=${{ secrets.TRELLO_DONE_LIST_ID }}"
          echo "TRELLO_REVIEW_LIST_ID=${{ secrets.TRELLO_REVIEW_LIST_ID }}"
          echo "GOOGLE_CREDENTIALS_JSON=${{ secrets.GOOGLE_CREDENTIALS_JSON }}"
          echo "GOOGLE_CALENDAR_ID=${{ secrets.GOOGLE_CALENDAR_ID }}"
        env:
          TRELLO_API_KEY: ${{ secrets.TRELLO_API_KEY }}
          TRELLO_API_TOKEN: ${{ secrets.TRELLO_API_TOKEN }}
          TRELLO_BOARD_ID: ${{ secrets.TRELLO_BOARD_ID }}
          TRELLO_WORKING_LIST_ID: ${{ secrets.TRELLO_WORKING_LIST_ID }}
          TRELLO_DONE_LIST_ID: ${{ secrets.TRELLO_DONE_LIST_ID }}
          TRELLO_REVIEW_LIST_ID: ${{ secrets.TRELLO_REVIEW_LIST_ID }}
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
          GOOGLE_CALENDAR_ID: ${{ secrets.GOOGLE_CALENDAR_ID }}

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run the Trello-Google Calendar sync script
        env:
          TRELLO_API_KEY: ${{ secrets.TRELLO_API_KEY }}
          TRELLO_API_TOKEN: ${{ secrets.TRELLO_API_TOKEN }}
          TRELLO_BOARD_ID: ${{ secrets.TRELLO_BOARD_ID }}
          TRELLO_WORKING_LIST_ID: ${{ secrets.TRELLO_WORKING_LIST_ID }}
          TRELLO_DONE_LIST_ID: ${{ secrets.TRELLO_DONE_LIST_ID }}
          TRELLO_REVIEW_LIST_ID: ${{ secrets.TRELLO_REVIEW_LIST_ID }}
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
          GOOGLE_CALENDAR_ID: ${{ secrets.GOOGLE_CALENDAR_ID }}
        run: |
          python trello_integration.py

